import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { Report, Trip, ReportStatus } from '../../models';
import { PageState } from '../../shared/ui';
import { IconComponent } from '../../shared/icon.component';
@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [FormsModule, IconComponent],
  template: ` <section class="page">
    <div class="page-heading">
      <div>
        <div class="eyebrow">BRING IT ALL TOGETHER</div>
        <h1>A clear picture of every journey<span class="title-dot">.</span></h1>
        <p>Save the details, review the totals, and share a polished summary.</p>
      </div>
      <button class="primary" (click)="open()" [disabled]="busy">
        <app-icon name="plus" />Create report
      </button>
    </div>
    @if (error) {
      <div class="error" role="alert"><app-icon name="alert" />{{ error }}</div>
    }
    @if (showForm) {
      <section class="form-box">
        <div class="form-heading">
          <div>
            <h2>One journey. Every detail.</h2>
            <p>Your report preserves the expenses as they are today.</p>
          </div>
          <button
            class="icon-button"
            aria-label="Close report form"
            (click)="showForm = false"
            [disabled]="busy"
          >
            <app-icon name="close" />
          </button>
        </div>
        <form #reportForm="ngForm" (ngSubmit)="generate(reportForm.valid)">
          <div class="form-row">
            <label
              >Trip<select name="trip_id" [(ngModel)]="tripId" required>
                <option [ngValue]="0" disabled>Select an approved trip</option>
                @for (trip of eligible; track trip.trip_id) {
                  <option [ngValue]="trip.trip_id">
                    {{ trip.destination }}{{ auth.isAdmin ? ' · ' + trip.user_name : '' }}
                  </option>
                }
              </select></label
            >
            <div class="report-total">
              <span>Total to include</span><strong>{{ money(selectedTrip?.spent) }}</strong>
            </div>
          </div>
          <small class="field-hint"
            >Generated by {{ auth.user?.first_name }} {{ auth.user?.last_name }}. Later expense
            edits will not change this saved report.</small
          >
          <div class="form-actions">
            <button class="primary" type="submit" [disabled]="busy || !eligible.length">
              {{ busy ? 'Creating…' : 'Create report' }}<app-icon name="reports" /></button
            ><button class="secondary" type="button" (click)="showForm = false" [disabled]="busy">
              Cancel
            </button>
          </div>
          @if (!eligible.length) {
            <p class="field-hint">You need an approved or completed trip to create a report.</p>
          }
        </form>
      </section>
    }
    <div class="toolbar">
      <div class="search-box">
        <app-icon name="search" /><input
          [(ngModel)]="search"
          aria-label="Search reports"
          placeholder="Search by destination…"
        />
      </div>
      <div class="filter-group">
        <span class="count-label">{{ counted(filtered.length, 'report') }}</span
        ><select [(ngModel)]="statusFilter" aria-label="Filter reports by status">
          <option value="">All statuses</option>
          <option value="GENERATED">Draft</option>
          <option value="SUBMITTED">Submitted</option>
          <option value="APPROVED">Approved</option>
        </select>
      </div>
    </div>
    @if (loading) {
      <div class="loading-state">Bringing it all together…</div>
    } @else {
      <div class="report-grid">
        @for (report of filtered; track report.report_id) {
          <article class="report-card">
            <div class="report-card-top">
              <span class="report-symbol"><app-icon name="reports" /></span>
              <div>
                <h2>
                  {{
                    report.snapshot?.trip?.destination || report.destination || 'Archived journey'
                  }}
                </h2>
                <p>
                  REPORT {{ report.report_id.toString().padStart(4, '0') }} ·
                  {{ date(report.generated_at) }}
                </p>
              </div>
              <span class="badge status-{{ report.report_status.toLowerCase() }}">{{
                reportLabel(report.report_status)
              }}</span>
            </div>
            <div class="report-total">
              <span>Total travel expenses</span><strong>{{ money(report.total_expenses) }}</strong>
            </div>
            <p class="report-detail">
              {{
                report.snapshot
                  ? counted(report.snapshot.expenses.length, 'expense') +
                    ', thoughtfully organized.'
                  : 'A summary of your travel spending.'
              }}<br />Prepared by {{ report.generated_by_name }}
            </p>
            <div class="report-actions">
              <a
                class="button primary"
                [href]="'/api/reports/' + report.report_id + '/pdf'"
                download
                ><app-icon name="download" />Export PDF</a
              >
              <a
                class="button secondary"
                [href]="'/api/reports/' + report.report_id + '/export'"
                download
                ><app-icon name="download" />Export CSV</a
              >
              @if (report.report_status === 'GENERATED') {
                <button class="primary" (click)="change(report, 'SUBMITTED')" [disabled]="busy">
                  Submit<app-icon name="arrow" />
                </button>
              }
              @if (auth.isAdmin && report.report_status === 'SUBMITTED') {
                <button class="primary" (click)="change(report, 'APPROVED')" [disabled]="busy">
                  <app-icon name="check" />Approve
                </button>
              }
              @if (auth.isAdmin || report.report_status === 'GENERATED') {
                <button
                  class="icon-button danger"
                  (click)="remove(report)"
                  [attr.aria-label]="'Delete report ' + report.report_id"
                  [disabled]="busy"
                >
                  <app-icon name="trash" />
                </button>
              }
            </div>
          </article>
        }
      </div>
      @if (!filtered.length) {
        <div class="empty-state">
          <app-icon name="reports" />
          <h3>
            {{
              reports.length ? 'No reports match your search.' : 'The full story, in one report.'
            }}
          </h3>
          <p>
            {{
              reports.length
                ? 'Try another destination or status.'
                : 'Create a summary of your trip expenses, ready to review and export.'
            }}
          </p>
          @if (!reports.length) {
            <button class="primary" (click)="open()">
              <app-icon name="plus" />Create your first report
            </button>
          }
        </div>
      }
    }
  </section>`,
})
export class ReportsComponent extends PageState implements OnInit {
  reports: Report[] = [];
  trips: Trip[] = [];
  search = '';
  statusFilter = '';
  showForm = false;
  tripId = 0;
  constructor(
    private api: ApiService,
    public auth: AuthService,
  ) {
    super();
  }
  ngOnInit() {
    this.load();
  }
  load() {
    this.run(
      forkJoin({ reports: this.api.getReports(), trips: this.api.getTrips() }),
      (data) => {
        this.reports = data.reports;
        this.trips = data.trips;
      },
      '',
      true,
    );
  }
  get eligible() {
    return this.trips.filter((t) => ['APPROVED', 'COMPLETED'].includes(t.status));
  }
  get selectedTrip() {
    return this.trips.find((t) => t.trip_id === this.tripId);
  }
  get filtered() {
    const q = this.search.trim().toLowerCase();
    return this.reports.filter(
      (r) =>
        (!this.statusFilter || r.report_status === this.statusFilter) &&
        (!q || (r.snapshot?.trip?.destination || r.destination || '').toLowerCase().includes(q)),
    );
  }
  open() {
    this.tripId = this.eligible[0]?.trip_id || 0;
    this.showForm = true;
    this.error = '';
  }
  generate(valid: boolean | null) {
    if (!valid || !this.tripId) {
      this.error = 'Select an approved trip to include in your report.';
      return;
    }
    this.run(
      this.api.createReport(this.tripId),
      () => {
        this.showForm = false;
        this.load();
      },
      'Report created. All the details, in one place.',
    );
  }
  change(report: Report, status: ReportStatus) {
    this.run(
      this.api.updateReportStatus(report.report_id, status),
      () => this.load(),
      status === 'APPROVED' ? 'Report approved.' : 'Report submitted for review.',
    );
  }
  remove(report: Report) {
    if (confirm('Delete this saved report? This cannot be undone.'))
      this.run(this.api.deleteReport(report.report_id), () => this.load(), 'Report deleted.');
  }
}
