const PNG_RECEIPT = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEUlEQVQYlWP4jxcwjEr/xwIA+h4q5HxTIAQAAAAASUVORK5CYII=',
  'base64',
);
module.exports = { PNG_RECEIPT };
